### ISSUE TITLE
Please add support for o3-mini-high and o1 from OpenRouter

### ISSUE THREAD

**Issue by it-sha** [paul-gauthier/aider#3228]
### Issue

https://openrouter.ai/openai/o3-mini-high
https://openrouter.ai/openai/o1

**Comment by gasatrya** [comment]
You can just use the original `openrouter/openai/o3-mini` then create `.aider.model.settings.yml`, add this:

```
- name: openrouter/openai/o3-mini
  extra_params:
    extra_body:
      reasoning_effort: high
```

Ref:
1. https://aider.chat/docs/llms/openai.html#reasoning-models-from-other-providers
2. https://aider.chat/docs/config/reasoning.html
3. https://aider.chat/docs/config/adv-model-settings.html
