### ISSUE TITLE
Feature: provide arguments when configuring test-cmd

### ISSUE THREAD

**Issue by Nucs** [paul-gauthier/aider#680]
### Issue

I am heavily relying on test-cmd to safely request new changes at it will retry for a few times to successfully add changes to code.
The problem is it can very well accept a single-word. It can't accept "dotnet test" or "pwsh -File test_file.ps1 arg1 arg2"

It would be helpful to have a way either to specify arguments separately or within the existing cfg property "test-cmd".
When specifying "dotnet test" or anything similar the error is: The filename, directory name, or volume label syntax is incorrect.

### Version and model info

Aider latest,
GPT-4o

**Comment by paul-gauthier** [comment]
Thanks for filing this issue. You can quote the multi-word test command like this:

```
aider --test-cmd "dotnet test"
```

For example:

```
$ aider --test-cmd "echo 1 2 3"
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 38 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────
> /test

1 2 3
```

**Comment by Nucs** [comment]
I've configured yml like this:
```yaml
## Specify command to run tests
test-cmd: "dotnet test"

## Enable/disable automatic testing after changes (default: False)
auto-test: true

## Run tests and fix problems found
test: true
```

And startup doesn't work properly and looks like this:
```
(aider) C:\workdir>aider
Aider v0.37.0
Model: openai/gpt-4o-2024-05-13 with diff edit format
Git repo: .git with 14 files
Repo-map: using 1024 tokens
'"dotnet test"' is not recognized as an internal or external command,
operable program or batch file.

```
