### ISSUE TITLE
Add lint-cmd and test-cmd values examples into documentation

### ISSUE THREAD

**Issue by rodion-m** [paul-gauthier/aider#909]
### Issue

I can provide examples for TypeScript and JavaScript:

```yml
lint-cmd: "npx @biomejs/biome lint --write "
auto-lint: true

test-cmd: "npm run build"
auto-test: true
```
It uses [biome linter](https://biomejs.dev/linter/).
